---
substitutions:
  device_name: slimmelezer
    
esphome:
  name: ${device_name}
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: d1_mini
  name_add_mac_suffix: false
  project:
    name: zuidwijk.slimmelezer
    version: "1.2"
  on_boot:
    then:
      - if:
          condition:
            lambda: return id(has_key);
          then:
            - lambda: |-
                std::string key(id(stored_decryption_key), 32);
                id(dsmr_instance).set_decryption_key(key);
          else:
            - logger.log:
                level: info
                format: "Not using decryption key. If you need to set a key use Home Assistant service 'ESPHome:  ${device_name}_set_dsmr_key'"

wifi:
  # remove leading '#' and fill in your wifi details
#  ssid: !secret wifi_ssid 
#  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}

captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

uart:
  baud_rate: 115200
  rx_pin: D7
  rx_buffer_size: 3072


dsmr:
  id: dsmr_instance
  max_telegram_length: 3072
  # For Luxembourg users set here your decryption key
  #decryption_key: !secret decryption_key // enable this when using decryption for Luxembourg; key like '00112233445566778899AABBCCDDEEFF'

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: ${friendly_name} Energy Delivered Tariff 1
      state_class: total_increasing
#    energy_delivered_tariff2:
#      name: ${friendly_name} Energy Delivered Tariff 2
#      state_class: total_increasing
    energy_returned_tariff1:
      name: ${friendly_name} Energy Returned Tariff 1
#    energy_returned_tariff2:
#      name: ${friendly_name} Energy Returned Tariff 2
    reactive_energy_delivered_tariff1:
        name: ${friendly_name} Reactiver Power Delivered 1
    reactive_energy_returned_tariff1:
        name: ${friendly_name} Reactiver Power Returned 1
    power_delivered:
      name: ${friendly_name} Power Consumed
      accuracy_decimals: 3
    power_returned:
      name: ${friendly_name} Power Returned
      accuracy_decimals: 3
    electricity_failures:
      name: ${friendly_name} Electricity Failures
      icon: mdi:alert
    electricity_long_failures:
      name: ${friendly_name} Electricity Long Failures
      icon: mdi:alert
    voltage:
      name: ${friendly_name} Voltage
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    voltage_l1:
      name: ${friendly_name} Voltage L1
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    voltage_avg_l1:
      name: ${friendly_name} Voltage average L1
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    voltage_l2:
      name: ${friendly_name} Voltage L2
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    voltage_avg_l2:
      name: ${friendly_name} Voltage average L2
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    voltage_l3:
      name: ${friendly_name} Voltage L3
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    voltage_avg_l3:
      name: ${friendly_name} Voltage average L3
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_l1:
      name: ${friendly_name} Current L1
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_fuse_l1:
      name: ${friendly_name} Current L1
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_l2:
      name: ${friendly_name} Current L2
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_fuse_l2:
      name: ${friendly_name} Current L2
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_l3:
      name: ${friendly_name} Current L3
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters: 
        multiply: 1000
    current_fuse_l3:
      name: ${friendly_name} Current L3
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current:
      name: ${friendly_name} Current
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_n:
      name: ${friendly_name} Current N
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_sum:
      name: ${friendly_name} Current sum
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    power_delivered_l1:
      name: ${friendly_name} Power Delivered L1
    power_delivered_l2:
      name: ${friendly_name} Power Delivered L2
    power_delivered_l3:
      name: ${friendly_name} Power Delivered L3
    power_returned_l1:
      name: ${friendly_name} Power Returned L1
    power_returned_l2:
      name: ${friendly_name} Power Returned L2
    power_returned_l3:
      name: ${friendly_name} Power Returned L3
    apparent_delivery_power:
      name: ${friendly_name} Apparent Power Deliverd
      filters:
        multiply: 1000
    apparent_delivery_power_l1:
      name: ${friendly_name} Apparent Power Deliverd L1
      filters:
        multiply: 1000
    apparent_delivery_power_l2:
      name: ${friendly_name} Apparent Power Deliverd L2
      filters:
        multiply: 1000
    apparent_delivery_power_l3:
      name: ${friendly_name} Apparent Power Deliverd L3
      filters:
        multiply: 1000
    apparent_return_power:
      name: ${friendly_name} Apparent Power Returned 
      filters:
        multiply: 1000
    apparent_return_power_l1:
      name: ${friendly_name} Apparent Power Returned L1
      filters:
        multiply: 1000
    apparent_return_power_l2:
      name: ${friendly_name} Apparent Power Returned L2
      filters:
        multiply: 1000
    apparent_return_power_l3:
      name: ${friendly_name} Apparent Power Returned L3
      filters:
        multiply: 1000
    active_demand_power:
      name: ${friendly_name} Active Demand Avg3
#    active_demand_net:
#      name: ${friendly_name} Active Demand Avg3 Net
    active_demand_abs:
      name: ${friendly_name} Active Demand Avg3 Absolute 
    reactive_power_delivered_l1:
      name: ${friendly_name} Reactive Power Delivered L1
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    reactive_power_delivered_l2:
      name: ${friendly_name} Reactive Power Delivered L2
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    reactive_power_delivered_l3:
      name: ${friendly_name} Reactive Power Delivered L3
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    reactive_power_returned_l1:
      name: ${friendly_name} Reactive Power Returned L1
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    reactive_power_returned_l2:
      name: ${friendly_name} Reactive Power Returned L2
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    reactive_power_returned_l3:
      name: ${friendly_name} Reactive Power Returned L3
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    active_energy_import_current_average_demand:
      name: ${friendly_name} Active Average Recive Demand
    active_energy_export_current_average_demand:
      name: ${friendly_name} Active Average Export Demand
    reactive_energy_import_current_average_demand:
      name: ${friendly_name} Reactive Average Recive Demand
    reactive_energy_export_current_average_demand:
      name: ${friendly_name} Reactive Average Export Demand
    apparent_energy_import_current_average_demand:
      name: ${friendly_name} Apparent Average Recive Demand
      filters:
        multiply: 1000
    apparent_energy_export_current_average_demand:
      name: ${friendly_name} Apparent Average Export Demand
      filters:
        multiply: 1000
    active_energy_import_last_completed_demand:
      name: ${friendly_name} Active Last Recive Demand
    active_energy_export_last_completed_demand:
      name: ${friendly_name} Active Last Export Demand
    reactive_energy_import_last_completed_demand:
      name: ${friendly_name} Reactive Last Recive Demand
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    reactive_energy_export_last_completed_demand:
      name: ${friendly_name} Reactive Last Export Demand
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    apparent_energy_import_last_completed_demand:
      name: ${friendly_name} Apparent Last Recive Demand
      filters:
        multiply: 1000
    apparent_energy_export_last_completed_demand:
      name: ${friendly_name} Apparent Last Export Demand
      filters:
        multiply: 1000
    fw_core_version:
      name: ${friendly_name} Core version
    fw_module_version:
      name: ${friendly_name} Module version
  - platform: uptime
    name: "SlimmeLezer Uptime"
  - platform: wifi_signal
    name: "SlimmeLezer Wi-Fi Signal"
    update_interval: 60s

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    fw_core_checksum:
      name: ${friendly_name} Core checskum
    fw_module_checksum:
      name: ${friendly_name} Module checskum
  - platform: wifi_info
    ip_address:
      name: "SlimmeLezer IP Address"
    ssid:
      name: "SlimmeLezer Wi-Fi SSID"
    bssid:
      name: "SlimmeLezer Wi-Fi BSSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
